---
- name: Install MariaDB
  apt:
    name: [mariadb-server, python3-pymysql]
    state: present
    update_cache: false

- name: Start MariaDB
  service:
    name: mariadb
    state: started
    enabled: true

- name: Create WordPress database
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create WordPress DB user
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ db_wp_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
