---
- name: Full WordPress stack
  hosts: all
  become: true
  vars_files:
    - ../vault.yml
  vars:
    wp_domain: opdracht3.sel.edu
    wp_path: /var/www/wordpress
    wp_db_name: wordpress
    wp_db_user: wpuser

  roles:
    - common
    - mariadb
    - wordpress
